name: gbu_attendx
description: GBU AttendX - Smart Attendance System for Gautam Buddha University

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core Services
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_functions: ^4.5.8
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+8

  # UI & Navigation
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Location & Biometric
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  local_auth: ^2.1.7
  camera: ^0.10.5+5

  # Charts & Calendar
  fl_chart: ^0.65.0
  table_calendar: ^3.0.9
  syncfusion_flutter_charts: ^23.2.7

  # Notifications & Background Tasks
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.10
  flutter_background_service: ^5.0.5

  # State Management & Architecture
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Network & HTTP
  http: ^1.1.2
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Storage & Utilities
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Utilities & Helpers
  intl: ^0.19.0
  uuid: ^4.2.1
  crypto: ^3.0.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1

  # Image Processing
  image: ^4.1.3
  flutter_image_compress: ^2.1.0

  # Security
  encrypt: ^5.0.1
  pointycastle: ^3.7.3

  # Development & Testing
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Linting & Code Quality
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # Code Generation
  freezed: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
